# Task A 
## Part 1: Extract data from the source adventureworks2012 database.

In [7]:
import mysql.connector
from sqlalchemy import create_engine
import pandas as pd

db_datawarehouse = mysql.connector.connect(
	host='localhost',
	user='bt4301',
	passwd='password',
	database='datawarehouse'
)

cursor = db_datawarehouse.cursor()
cursor.execute('DROP TABLE IF EXISTS sales;')
cursor.execute('DROP TABLE IF EXISTS customer;')
cursor.execute('DROP TABLE IF EXISTS product;')
cursor.execute('DROP TABLE IF EXISTS salesordertime;')
cursor.execute('DROP TABLE IF EXISTS salesperson;')

db_datawarehouse.commit()
db_datawarehouse.close()

In [8]:
db_adventureworks2012 = mysql.connector.connect(
	host='localhost',
	user='bt4301',
	passwd='password',
	database='adventureworks2012'
)

engine = create_engine('mysql+mysqlconnector://bt4301:password@localhost:3306/datawarehouse', echo=False)

In [9]:
# Ingest customer dimension

str_sql = '''
SELECT 
    customer.CustomerID,
    store.SalesPersonID AS SalesPersonID,
    customer.PersonID AS CustomerPersonID,
    customer.StoreID AS CustomerStoreID,
    customer.AccountNumber,
    store.Name AS StoretName,
    address.AddressLine1 AS AddressLine1, address.AddressLine2 AS AddressLine2, address.City AS City,
    address.PostalCode AS PostalCode, stateprovince.Name AS StateProvinceName, countryregion.Name AS CountryName
FROM customer 
    INNER JOIN store ON customer.StoreID = store.BusinessEntityID
    INNER JOIN businessentity ON store.BusinessEntityID = businessentity.BusinessEntityID
    LEFT JOIN businessentityaddress ON store.BusinessEntityID = businessentityaddress.BusinessEntityID
    LEFT JOIN address ON businessentityaddress.AddressID = address.AddressID
    LEFT JOIN stateprovince ON address.StateProvinceID = stateprovince.StateProvinceID
    LEFT JOIN countryregion ON stateprovince.CountryRegionCode = countryregion.CountryRegionCode
WHERE customer.StoreID IS NOT NULL AND customer.PersonID IS NOT NULL AND businessentityaddress.AddressTypeID = 3
ORDER BY customer.StoreID ASC;
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
print(len(df))
df.head()

635

/tmp/ipykernel_14508/968254915.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,CustomerID,SalesPersonID,CustomerPersonID,CustomerStoreID,AccountNumber,StoretName,AddressLine1,AddressLine2,City,PostalCode,StateProvinceName,CountryName
0,29484,279,291,292,AW00029484,Next-Door Bike Store,Mall Of Memphis,None,Memphis,38103,Tennessee,United States
1,29485,276,293,294,AW00029485,Professional Sales and Service,57251 Serene Blvd,None,Van Nuys,91411,California,United States
2,29486,277,295,296,AW00029486,Riders Company,Tanger Factory,None,Branch,55056,Minnesota,United States
3,29487,275,297,298,AW00029487,The Bike Mechanics,Johnny Appleseed Shop.center,None,Mansfield,44903,Ohio,United States
4,29488,286,299,300,AW00029488,Nationwide Supply,4250 Concord Road,None,Rhodes,2138,New South Wales,Australia

In [10]:
# load customer dimension
db_datawarehouse = engine.connect()
df.to_sql(name='customer', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

In [11]:
# Ingest product dimension

str_sql = '''
SELECT product.ProductID, product.ProductNumber, product.Name, product.Color, product.StandardCost, product.ListPrice, product.Size, product.SizeUnitMeasureCode, product.Weight, product.WeightUnitMeasureCode, product.ProductLine, product.Class, product.Style, productmodel.Name AS ProductModelName, productsubcategory.Name AS ProductSubCategoryName, productcategory.Name AS ProductCategoryName
FROM product
    INNER JOIN productmodel ON product.ProductModelID = productmodel.ProductModelID
    INNER JOIN productsubcategory on product.ProductSubcategoryID = productsubcategory.ProductSubcategoryID
    INNER JOIN productcategory on productsubcategory.ProductCategoryID = productcategory.ProductCategoryID
ORDER BY product.ProductID ASC;
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
df

/tmp/ipykernel_14508/952403414.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,ProductID,ProductNumber,Name,Color,StandardCost,ListPrice,Size,SizeUnitMeasureCode,Weight,WeightUnitMeasureCode,ProductLine,Class,Style,ProductModelName,ProductSubCategoryName,ProductCategoryName
0,680,FR-R92B-58,"HL Road Frame - Black, 58",Black,1059.3100,1431.50,58,CM,2.24,LB,R,H,U,HL Road Frame,Road Frames,Components
1,706,FR-R92R-58,"HL Road Frame - Red, 58",Red,1059.3100,1431.50,58,CM,2.24,LB,R,H,U,HL Road Frame,Road Frames,Components
2,707,HL-U509-R,"Sport-100 Helmet, Red",Red,13.0863,34.99,None,None,NaN,None,S,None,None,Sport-100,Helmets,Accessories
3,708,HL-U509,"Sport-100 Helmet, Black",Black,13.0863,34.99,None,None,NaN,None,S,None,None,Sport-100,Helmets,Accessories
4,709,SO-B909-M,"Mountain Bike Socks, M",White,3.3963,9.50,M,None,NaN,None,M,None,U,Mountain Bike Socks,Socks,Clothing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,995,BB-8107,ML Bottom Bracket,None,44.9506,101.24,None,None,168.00,G,None,M,None,ML Bottom Bracket,Bottom Brackets,Components
291,996,BB-9108,HL Bottom Bracket,None,53.9416,121.49,None,None,170.00,G,None,H,None,HL Bottom Bracket,Bottom Brackets,Components
292,997,BK-R19B-44,"Road-750 Black, 44",Black,343.6496,539.99,44,CM,19.77,LB,R,L,U,Road-750,Road Bikes,Bikes
293,998,BK-R19B-48,"Road-750 Black, 48",Black,343.6496,539.99,48,CM,20.13,LB,R,L,U,Road-750,Road Bikes,Bikes
294,999,BK-R19B-52,"Road-750 Black, 52",Black,343.6496,539.99,52,CM,20.42,LB,R,L,U,Road-750,Road Bikes,Bikes

In [12]:
# load product dimension

df.to_sql(name='product', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

In [13]:
str_sql = '''
SELECT SalesOrderID, OrderDate, YEAR(OrderDate) AS OrderDateYear, MONTH(OrderDate) AS OrderDateMonth, Day(OrderDate) AS OrderDateDay, IF((DayOfWeek(OrderDate) - 1) = 0, 7, DayOfWeek(OrderDate) - 1) As OrderDateDayOfWeek, WEEK(OrderDate) AS OrderDateWeek
FROM salesorderheader
WHERE OnlineOrderFlag = 0
ORDER BY SalesOrderID ASC;
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
df

/tmp/ipykernel_14508/3107842179.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,SalesOrderID,OrderDate,OrderDateYear,OrderDateMonth,OrderDateDay,OrderDateDayOfWeek,OrderDateWeek
0,43659,2005-07-01,2005,7,1,5,26
1,43660,2005-07-01,2005,7,1,5,26
2,43661,2005-07-01,2005,7,1,5,26
3,43662,2005-07-01,2005,7,1,5,26
4,43663,2005-07-01,2005,7,1,5,26
...,...,...,...,...,...,...,...
3801,71948,2008-06-01,2008,6,1,7,22
3802,71949,2008-06-01,2008,6,1,7,22
3803,71950,2008-06-01,2008,6,1,7,22
3804,71951,2008-06-01,2008,6,1,7,22
3805,71952,2008-06-01,2008,6,1,7,22

In [14]:
# load time dimension

df.to_sql(name='salesordertime', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

## Part 2: Implementing sales person table

In [15]:
str_sql = '''
SELECT 
    salesperson.BusinessEntityID as SalesPersonID, salesperson.SalesQuota, salesperson.Bonus,
    salesperson.CommissionPct, salesperson.SalesYTD, salesperson.SalesLastYear
FROM salesperson
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
df

/tmp/ipykernel_14508/1465040002.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,SalesPersonID,SalesQuota,Bonus,CommissionPct,SalesYTD,SalesLastYear
0,274,NaN,0.0,0.000,5.596976e+05,0.000000e+00
1,275,300000.0,4100.0,0.012,3.763178e+06,1.750406e+06
2,276,250000.0,2000.0,0.015,4.251369e+06,1.439156e+06
3,277,250000.0,2500.0,0.015,3.189418e+06,1.997186e+06
4,278,250000.0,500.0,0.010,1.453719e+06,1.620277e+06
5,279,300000.0,6700.0,0.010,2.315186e+06,1.849641e+06
6,280,250000.0,5000.0,0.010,1.352577e+06,1.927059e+06
7,281,250000.0,3550.0,0.010,2.458536e+06,2.073506e+06
8,282,250000.0,5000.0,0.015,2.604541e+06,2.038235e+06
9,283,250000.0,3500.0,0.012,1.573013e+06,1.371635e+06
10,284,300000.0,3900.0,0.019,1.576562e+06,0.000000e+00
11,285,NaN,0.0,0.000,1.725245e+05,0.000000e+00
12,286,250000.0,5650.0,0.018,1.421811e+06,2.278549e+06
13,287,NaN,0.0,0.000,5.199059e+05,0.000000e+00
14,288,250000.0,75.0,0.018,1.827067e+06,1.307950e+06
15,289,250000.0,5150.0,0.020,4.116871e+06,1.635823e+06
16,290,250000.0,985.0,0.016,3.121616e+06,2.396540e+06

In [16]:
df.to_sql(name='salesperson', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

## Part 3: three data transformations to the salesfact

In [17]:
try:
    db_adventureworks2012.close()
except:
    pass
db_adventureworks2012 = mysql.connector.connect(
    host='localhost',
    user='bt4301',
    passwd='password',
    database='adventureworks2012'
)

str_sql = '''
SELECT 
    salesorderdetail.SalesOrderID, salesorderdetail.SalesOrderDetailID, salesorderdetail.ProductID, 
    salesorderdetail.OrderQty, salesorderdetail.UnitPrice, salesorderdetail.UnitPriceDiscount,
    salesorderdetail.LineTotal, salesorderheader.CustomerID,
    -- Transformation 1: Discount amount
    salesorderdetail.UnitPrice * salesorderdetail.OrderQty * salesorderdetail.UnitPriceDiscount AS DiscountAmount,
    -- Transformation 2: Cost of goods sold
    prod.StandardCost * salesorderdetail.OrderQty AS CostOfGoodsSold,
    -- Transformation 3: Gross profit (Revenue - COGS)
    salesorderdetail.LineTotal - (prod.StandardCost * salesorderdetail.OrderQty) AS GrossProfit
FROM salesorderdetail
    INNER JOIN salesorderheader ON salesorderdetail.SalesOrderID = salesorderheader.SalesOrderID
    INNER JOIN datawarehouse.customer dw_cust ON salesorderheader.CustomerID = dw_cust.CustomerID
    INNER JOIN datawarehouse.product prod ON salesorderdetail.ProductID = prod.ProductID
WHERE salesorderheader.OnlineOrderFlag = 0   
ORDER BY salesorderdetail.SalesOrderID, salesorderdetail.SalesOrderDetailID ASC;
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
df

/tmp/ipykernel_14508/2413642605.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,SalesOrderID,SalesOrderDetailID,ProductID,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal,CustomerID,DiscountAmount,CostOfGoodsSold,GrossProfit
0,43659,1,776,1,2024.994,0.0,2024.9940,29825,0.0000,1898.0944,126.8996
1,43659,2,777,3,2024.994,0.0,6074.9820,29825,0.0000,5694.2832,380.6988
2,43659,3,778,1,2024.994,0.0,2024.9940,29825,0.0000,1898.0944,126.8996
3,43659,4,771,1,2039.994,0.0,2039.9940,29825,0.0000,1912.1544,127.8396
4,43659,5,772,1,2039.994,0.0,2039.9940,29825,0.0000,1912.1544,127.8396
...,...,...,...,...,...,...,...,...,...,...,...
60914,71952,113559,920,2,158.430,0.0,316.8600,30046,0.0000,289.1876,27.6724
60915,71952,113560,743,1,809.760,0.0,809.7600,30046,0.0000,739.0410,70.7190
60916,71952,113561,742,4,818.700,0.0,3274.8000,30046,0.0000,2988.8008,285.9992
60917,71952,113562,994,3,32.394,0.0,97.1820,30046,0.0000,71.9148,25.2672
60918,71952,113563,985,3,112.998,0.4,203.3964,30046,135.5976,924.6537,-721.2573

In [18]:
# load sales fact
df.to_sql(name='sales', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

In [19]:
#  close database connections

db_adventureworks2012.close()
db_datawarehouse.close()

In [20]:
#  housekeeping - set up primary and foreign keys in datawarehouse

db_datawarehouse = mysql.connector.connect(
	host='localhost',
	user='bt4301',
	passwd='password',
	database='datawarehouse'
)

cursor = db_datawarehouse.cursor()
cursor.execute('ALTER TABLE customer ADD PRIMARY KEY (CustomerID);')
cursor.execute('ALTER TABLE customer ADD INDEX idx_salespersonid (SalesPersonID);')
cursor.execute('ALTER TABLE product ADD PRIMARY KEY (ProductID);')
cursor.execute('ALTER TABLE salesordertime ADD PRIMARY KEY (SalesOrderID);')
cursor.execute('ALTER TABLE sales ADD PRIMARY KEY (SalesOrderID, SalesOrderDetailID);')
cursor.execute('ALTER TABLE sales ADD FOREIGN KEY (CustomerID) REFERENCES customer(CustomerID);')
cursor.execute('ALTER TABLE sales ADD FOREIGN KEY (ProductID) REFERENCES product(ProductID);')
cursor.execute('ALTER TABLE sales ADD FOREIGN KEY (SalesOrderID) REFERENCES salesordertime(SalesOrderID);')
cursor.execute('ALTER TABLE salesperson ADD PRIMARY KEY (SalesPersonID);')

db_datawarehouse.commit()
db_datawarehouse.close()