In [6]:
import mysql.connector
from sqlalchemy import create_engine
import pandas as pd

In [7]:
#  housekeeping - drop existing tables in datawarehouse

db_datawarehouse = mysql.connector.connect(
	host='localhost',
	user='bt4301',
	passwd='password',
	database='datawarehouse'
)

cursor = db_datawarehouse.cursor()
cursor.execute('DROP TABLE IF EXISTS sales;')
cursor.execute('DROP TABLE IF EXISTS customer;')
cursor.execute('DROP TABLE IF EXISTS product;')
cursor.execute('DROP TABLE IF EXISTS salesordertime;')

db_datawarehouse.commit()
db_datawarehouse.close()

In [8]:
db_adventureworks2012 = mysql.connector.connect(
	host='localhost',
	user='bt4301',
	passwd='password',
	database='adventureworks2012'
)

engine = create_engine('mysql://bt4301:password@localhost:3306/datawarehouse', echo=False)
db_datawarehouse = engine.connect()

In [9]:
# Ingest customer dimension

str_sql = '''
SELECT customer.CustomerID, customer.PersonID AS CustomerPersonID, customer.AccountNumber, person.NameStyle, person.Title, person.FirstName, person.MiddleName, person.LastName, person.EmailPromotion, address.AddressLine1, address.AddressLine2, address.City, address.PostalCode, stateprovince.Name AS StateProvinceName, countryregion.Name AS CountryName
FROM customer 
    INNER JOIN person ON customer.PersonID = person.BusinessEntityID
    INNER JOIN businessentity on person.BusinessEntityID = businessentity.BusinessEntityID
    INNER JOIN businessentityaddress on businessentity.BusinessEntityID = businessentityaddress.BusinessEntityID
    INNER JOIN address on businessentityaddress.AddressID = address.AddressID
    INNER JOIN stateprovince on address.StateProvinceID = stateprovince.StateProvinceID
    INNER JOIN countryregion on stateprovince.CountryRegionCode = countryregion.CountryRegionCode
WHERE PersonID IS NOT NULL AND StoreID IS NULL
    AND businessentityaddress.AddressTypeID = 2
ORDER BY customer.CustomerID ASC;
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
df

/tmp/ipykernel_11900/4120896907.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,CustomerID,CustomerPersonID,AccountNumber,NameStyle,Title,FirstName,MiddleName,LastName,EmailPromotion,AddressLine1,AddressLine2,City,PostalCode,StateProvinceName,CountryName
0,11000,13531,AW00011000,0,None,Jon,V,Yang,1,3761 N. 14th St,None,Rockhampton,4700,Queensland,Australia
1,11001,5454,AW00011001,0,None,Eugene,L,Huang,0,2243 W St.,None,Seaford,3198,Victoria,Australia
2,11002,11269,AW00011002,0,None,Ruben,None,Torres,2,5844 Linden Land,None,Hobart,7001,Tasmania,Australia
3,11003,11358,AW00011003,0,None,Christy,None,Zhu,0,1825 Village Pl.,None,North Ryde,2113,New South Wales,Australia
4,11004,11901,AW00011004,0,None,Elizabeth,None,Johnson,1,7553 Harness Circle,None,Wollongong,2500,New South Wales,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18479,29479,4191,AW00029479,0,None,Tommy,L,Tang,2,"111, rue Maillard",None,Versailles,78000,Yveline,France
18480,29480,4472,AW00029480,0,None,Nina,W,Raji,0,9 Katherine Drive,None,London,SW19 3RU,England,United Kingdom
18481,29481,8168,AW00029481,0,None,Ivan,None,Suri,0,Knaackstr 4,None,Hof,95010,Bayern,Germany
18482,29482,12570,AW00029482,0,None,Clayton,None,Zhang,1,"1080, quai de Grenelle",None,Saint Ouen,17490,Charente-Maritime,France
18483,29483,18384,AW00029483,0,None,Jésus,L,Navarro,0,"244, rue de la Centenaire",None,Paris La Defense,92081,Hauts de Seine,France

In [10]:
# load customer dimension

df.to_sql(name='customer', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

/tmp/ipykernel_11900/4034584524.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df.to_sql(name='customer', con=db_datawarehouse, if_exists='replace')

AttributeError: 'Connection' object has no attribute 'cursor'

In [ ]:
# Ingest product dimension

str_sql = '''
SELECT product.ProductID, product.ProductNumber, product.Name, product.Color, product.StandardCost, product.ListPrice, product.Size, product.SizeUnitMeasureCode, product.Weight, product.WeightUnitMeasureCode, product.ProductLine, product.Class, product.Style, productmodel.Name AS ProductModelName, productsubcategory.Name AS ProductSubCategoryName, productcategory.Name AS ProductCategoryName
FROM product
    INNER JOIN productmodel ON product.ProductModelID = productmodel.ProductModelID
    INNER JOIN productsubcategory on product.ProductSubcategoryID = productsubcategory.ProductSubcategoryID
    INNER JOIN productcategory on productsubcategory.ProductCategoryID = productcategory.ProductCategoryID
ORDER BY product.ProductID ASC;
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
df

/tmp/ipykernel_14759/952403414.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,ProductID,ProductNumber,Name,Color,StandardCost,ListPrice,Size,SizeUnitMeasureCode,Weight,WeightUnitMeasureCode,ProductLine,Class,Style,ProductModelName,ProductSubCategoryName,ProductCategoryName
0,680,FR-R92B-58,"HL Road Frame - Black, 58",Black,1059.3100,1431.50,58,CM,2.24,LB,R,H,U,HL Road Frame,Road Frames,Components
1,706,FR-R92R-58,"HL Road Frame - Red, 58",Red,1059.3100,1431.50,58,CM,2.24,LB,R,H,U,HL Road Frame,Road Frames,Components
2,707,HL-U509-R,"Sport-100 Helmet, Red",Red,13.0863,34.99,NaN,NaN,NaN,NaN,S,NaN,NaN,Sport-100,Helmets,Accessories
3,708,HL-U509,"Sport-100 Helmet, Black",Black,13.0863,34.99,NaN,NaN,NaN,NaN,S,NaN,NaN,Sport-100,Helmets,Accessories
4,709,SO-B909-M,"Mountain Bike Socks, M",White,3.3963,9.50,M,NaN,NaN,NaN,M,NaN,U,Mountain Bike Socks,Socks,Clothing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,995,BB-8107,ML Bottom Bracket,NaN,44.9506,101.24,NaN,NaN,168.00,G,NaN,M,NaN,ML Bottom Bracket,Bottom Brackets,Components
291,996,BB-9108,HL Bottom Bracket,NaN,53.9416,121.49,NaN,NaN,170.00,G,NaN,H,NaN,HL Bottom Bracket,Bottom Brackets,Components
292,997,BK-R19B-44,"Road-750 Black, 44",Black,343.6496,539.99,44,CM,19.77,LB,R,L,U,Road-750,Road Bikes,Bikes
293,998,BK-R19B-48,"Road-750 Black, 48",Black,343.6496,539.99,48,CM,20.13,LB,R,L,U,Road-750,Road Bikes,Bikes
294,999,BK-R19B-52,"Road-750 Black, 52",Black,343.6496,539.99,52,CM,20.42,LB,R,L,U,Road-750,Road Bikes,Bikes

In [ ]:
# load product dimension

df.to_sql(name='product', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

In [ ]:
# ingest time dimension

str_sql = '''
SELECT SalesOrderID, OrderDate, YEAR(OrderDate) AS OrderDateYear, MONTH(OrderDate) AS OrderDateMonth, Day(OrderDate) AS OrderDateDay, IF((DayOfWeek(OrderDate) - 1) = 0, 7, DayOfWeek(OrderDate) - 1) As OrderDateDayOfWeek, WEEK(OrderDate) AS OrderDateWeek
FROM salesorderheader
WHERE OnlineOrderFlag = 1
ORDER BY SalesOrderID ASC;
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
df

/tmp/ipykernel_14759/520865176.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,SalesOrderID,OrderDate,OrderDateYear,OrderDateMonth,OrderDateDay,OrderDateDayOfWeek,OrderDateWeek
0,43697,2005-07-01,2005,7,1,5,26
1,43698,2005-07-01,2005,7,1,5,26
2,43699,2005-07-01,2005,7,1,5,26
3,43700,2005-07-01,2005,7,1,5,26
4,43701,2005-07-01,2005,7,1,5,26
...,...,...,...,...,...,...,...
27654,75119,2008-07-31,2008,7,31,4,30
27655,75120,2008-07-31,2008,7,31,4,30
27656,75121,2008-07-31,2008,7,31,4,30
27657,75122,2008-07-31,2008,7,31,4,30
27658,75123,2008-07-31,2008,7,31,4,30

In [ ]:
# load time dimension

df.to_sql(name='salesordertime', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

In [ ]:
# ingest sales fact

str_sql = '''
SELECT salesorderdetail.SalesOrderID, salesorderdetail.SalesOrderDetailID, salesorderdetail.ProductID, salesorderdetail.OrderQty, salesorderdetail.UnitPrice, salesorderdetail.UnitPriceDiscount, salesorderdetail.LineTotal, salesorderheader.CustomerID
FROM salesorderdetail
    INNER JOIN salesorderheader ON salesorderdetail.SalesOrderID = salesorderheader.SalesOrderID
WHERE salesorderheader.OnlineOrderFlag = 1    
ORDER BY salesorderdetail.SalesOrderID, salesorderdetail.SalesOrderDetailID ASC;
'''
df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)
df

/tmp/ipykernel_14759/1138126074.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql=str_sql, con=db_adventureworks2012)

,SalesOrderID,SalesOrderDetailID,ProductID,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal,CustomerID
0,43697,353,749,1,3578.2700,0.0,3578.2700,21768
1,43698,354,773,1,3399.9900,0.0,3399.9900,28389
2,43699,355,773,1,3399.9900,0.0,3399.9900,25863
3,43700,356,767,1,699.0982,0.0,699.0982,14501
4,43701,357,773,1,3399.9900,0.0,3399.9900,11003
...,...,...,...,...,...,...,...,...
60393,75122,121313,878,1,21.9800,0.0,21.9800,15868
60394,75122,121314,712,1,8.9900,0.0,8.9900,15868
60395,75123,121315,878,1,21.9800,0.0,21.9800,18759
60396,75123,121316,879,1,159.0000,0.0,159.0000,18759
60397,75123,121317,712,1,8.9900,0.0,8.9900,18759

In [ ]:
# load sales fact

df.to_sql(name='sales', con=db_datawarehouse, if_exists='replace')
db_datawarehouse.commit()

In [ ]:
#  close database connections

db_adventureworks2012.close()
db_datawarehouse.close()

In [ ]:
#  housekeeping - set up primary and foreign keys in datawarehouse

db_datawarehouse = mysql.connector.connect(
	host='localhost',
	user='bt4301',
	passwd='password',
	database='datawarehouse'
)

cursor = db_datawarehouse.cursor()
cursor.execute('ALTER TABLE customer ADD PRIMARY KEY (CustomerID);')
cursor.execute('ALTER TABLE product ADD PRIMARY KEY (ProductID);')
cursor.execute('ALTER TABLE salesordertime ADD PRIMARY KEY (SalesOrderID);')
cursor.execute('ALTER TABLE sales ADD PRIMARY KEY (SalesOrderID, SalesOrderDetailID);')
cursor.execute('ALTER TABLE sales ADD FOREIGN KEY (CustomerID) REFERENCES customer(CustomerID);')
cursor.execute('ALTER TABLE sales ADD FOREIGN KEY (ProductID) REFERENCES product(ProductID);')
cursor.execute('ALTER TABLE sales ADD FOREIGN KEY (SalesOrderID) REFERENCES salesordertime(SalesOrderID);')

db_datawarehouse.commit()
db_datawarehouse.close()

: